### ISSUE TITLE
Crash after trying to load Spine file with System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by ItsTheWolf** [kiletw/SpineViewerWPF#22]
.NET Framework 4.7.2 has been installed
Microsoft XNA Framework Redistributable 4.0 has been installed (and reinstalled)

Crash after trying to load Spine file.

Event viewer log:

```
Faulting application name: SpineViewerWPF.exe, version: 2.3.1.0, time stamp: 0x614a904d
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1586, time stamp: 0xe89e47cc
Exception code: 0xe0434352
Fault offset: 0x0012b922
Faulting process id: 0x378c
Faulting application start time: 0x01d8383cb62048b7
Faulting application path: C:\Users\user\Downloads\SpineViewerWPF.v2.3.1.0\SpineViewerWPF.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: d2a249f1-e258-4346-87d2-39a04631f7d0
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Application: SpineViewerWPF.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess)
   at Util.LoadTexture(Microsoft.Xna.Framework.Graphics.GraphicsDevice, System.String)
   at Spine3_6_53.XnaTextureLoader.Load(Spine3_6_53.AtlasPage, System.String)
   at Spine3_6_53.Atlas.Load(System.IO.TextReader, System.String, Spine3_6_53.TextureLoader)
   at Spine3_6_53.Atlas..ctor(System.String, Spine3_6_53.TextureLoader)

Exception Info: System.Exception
   at Spine3_6_53.Atlas..ctor(System.String, Spine3_6_53.TextureLoader)
   at Player_3_6_53.LoadContent(Microsoft.Xna.Framework.Content.ContentManager)
   at WpfXnaControl.XnaControl.XnaControl_Loaded(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(System.Windows.DependencyObject, System.Windows.RoutedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(System.Object)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at SpineViewerWPF.App.Main()
```

Spine file attached:
[Kokkoro 1.zip](https://github.com/kiletw/SpineViewerWPF/files/8251141/Kokkoro.1.zip)

**Comment by kiletw** [comment]
Because of the texture name in altas is named 105911.png not Kokkoro 1.png. So you can rename the texture file to let it work.
